name: random_color_generator
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  solid_lints: ^0.0.14
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  pubspec_dependency_sorter: ^1.0.3
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
